// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDo3CihiPFGYZiBlb5oDVmN0w0D81Y3XM',
    appId: '1:300740685154:web:f7df059822de5e2b16903b',
    messagingSenderId: '300740685154',
    projectId: 'driveprofit-b1a32',
    authDomain: 'driveprofit-b1a32.firebaseapp.com',
    storageBucket: 'driveprofit-b1a32.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqOYhkEnglMKksvjgU813d17vcpz3OcsU',
    appId: '1:300740685154:android:2265af86f6429bf016903b',
    messagingSenderId: '300740685154',
    projectId: 'driveprofit-b1a32',
    storageBucket: 'driveprofit-b1a32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARufYi8jbqQvakhNWT2ph0fGkoXAm9gME',
    appId: '1:300740685154:ios:01076d57052afd5216903b',
    messagingSenderId: '300740685154',
    projectId: 'driveprofit-b1a32',
    storageBucket: 'driveprofit-b1a32.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
